# Generated by Django 5.2.11 on 2026-05-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCloverOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('payload', models.JSONField()),
                ('clover_checkout_id', models.CharField(blank=True, max_length=255, null=True)),
                ('clover_checkout_url', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(default='PENDING', max_length=30)),
                ('invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
